In [106]:
import pandas as pd
import requests

In [107]:
response=requests.get('https://api.themoviedb.org/3/movie/popular?api_key=d08bc87cb6dc6a0074b4c8fe8a4e7514&language=en-US&page=1')

In [108]:
df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [109]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1368337,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",2026-07-15,746.6132,7.820,713
1,1108427,Moana,"Teenage Moana answers the Ocean's call and, fo...",2026-07-08,601.7817,5.788,117
2,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...",2026-05-13,573.6836,8.250,3346
3,1083381,Backrooms,A strange doorway appears in the basement of a...,2026-05-27,453.2348,7.047,1772
4,1275779,Disclosure Day,A cybersecurity expert becomes a whistleblower...,2026-06-10,452.1308,6.700,905

In [110]:
df=pd.DataFrame()

In [111]:
df

Empty DataFrame
Columns: []
Index: []

In [113]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/popular?api_key=d08bc87cb6dc6a0074b4c8fe8a4e7514&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df,temp_df],ignore_index=True)

In [114]:
df.shape

(10640, 7)

In [115]:
df.to_csv('movies.csv')